# Generated by Django 5.2.17 on 2026-09-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='stones/'),
        ),
    ]
