# Generated by Django 5.2.17 on 2026-09-25 18:15

from django.db import migrations, models


def normalize_regions(apps, schema_editor):
    """Rewrite hand-typed regions as region values where they are unambiguous.

    Text that names no region clearly - a town, a typo, plain "Zanzibar" - is
    left exactly as it was: the edit form asks for the region next time the
    customer is saved, rather than this migration throwing the text away.
    Soft-deleted customers too, through the base manager.

    Imports the normalizer rather than copying it, so the migration reads regions
    the way the app does; if that module ever moves, inline it here.
    """
    from apps.gems.regions import normalize_region

    customers = apps.get_model("orders", "Customer")._base_manager
    for customer in customers.exclude(region="").only("id", "region"):
        value = normalize_region(customer.region)
        if value and value != customer.region:
            customers.filter(pk=customer.pk).update(region=value)


def restore_labels(apps, schema_editor):
    """Undo: each region value goes back to its readable name."""
    from apps.gems.enums import Region

    customers = apps.get_model("orders", "Customer")._base_manager
    for value, label in Region.choices:
        customers.filter(region=value).update(region=label)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_order_held_at_order_held_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.CharField(blank=True, choices=[('arusha', 'Arusha'), ('dar_es_salaam', 'Dar es Salaam'), ('dodoma', 'Dodoma'), ('geita', 'Geita'), ('iringa', 'Iringa'), ('kagera', 'Kagera'), ('katavi', 'Katavi'), ('kigoma', 'Kigoma'), ('kilimanjaro', 'Kilimanjaro'), ('lindi', 'Lindi'), ('manyara', 'Manyara'), ('mara', 'Mara'), ('mbeya', 'Mbeya'), ('morogoro', 'Morogoro'), ('mtwara', 'Mtwara'), ('mwanza', 'Mwanza'), ('njombe', 'Njombe'), ('pwani', 'Pwani'), ('rukwa', 'Rukwa'), ('ruvuma', 'Ruvuma'), ('shinyanga', 'Shinyanga'), ('simiyu', 'Simiyu'), ('singida', 'Singida'), ('songwe', 'Songwe'), ('tabora', 'Tabora'), ('tanga', 'Tanga'), ('kaskazini_pemba', 'Kaskazini Pemba'), ('kaskazini_unguja', 'Kaskazini Unguja'), ('kusini_pemba', 'Kusini Pemba'), ('kusini_unguja', 'Kusini Unguja'), ('mjini_magharibi', 'Mjini Magharibi')], default='', max_length=100),
        ),
        migrations.RunPython(normalize_regions, restore_labels),
    ]
