# Generated by Django 5.2.17 on 2026-09-09 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gems", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentificationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("report_number", models.CharField(max_length=50)),
                (
                    "nature_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("natural", "Natural"),
                            ("synthetic", "Synthetic"),
                            ("treated", "Treated"),
                            ("enhanced", "Enhanced"),
                            ("artificial", "Artificial"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "transparency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("transparent", "Transparent"),
                            ("translucent", "Translucent"),
                            ("opaque", "Opaque"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "treatment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("heated", "Heated"),
                            ("oiled", "Oiled"),
                            ("dyed", "Dyed"),
                            ("irradiated", "Irradiated"),
                            ("fracture_filled", "Fracture filled"),
                            ("bleached", "Bleached"),
                            ("impregnated", "Impregnated"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "optic_character",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sr", "SR - Singly refractive"),
                            ("adr", "ADR - Anomalous double refractive"),
                            ("dr", "DR - Double refractive"),
                            ("agg", "AGG - Aggregate"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("dimensions", models.CharField(blank=True, default="", max_length=50)),
                (
                    "refractive_index",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "specific_gravity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("is_polished", models.BooleanField(default=False)),
                ("conclusion", models.TextField(blank=True, default="")),
                ("is_finalized", models.BooleanField(default=False)),
                ("identified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="gems.color",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "identified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="gems.origin",
                    ),
                ),
                (
                    "shape_cut",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="gems.shapecut",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="gems.species",
                    ),
                ),
                (
                    "stone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="orders.stone",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variety",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="gems.variety",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("finalize_report", "Can finalize an identification report")
                ],
            },
        ),
        migrations.CreateModel(
            name="InstrumentUsed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("reading", models.CharField(blank=True, default="", max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="gems.instrument",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instruments_used",
                        to="identification.identificationreport",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["report", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="identificationreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("report_number",),
                name="identification_identificationreport_unique_report_number",
            ),
        ),
    ]
