# Generated by Django 5.2.17 on 2026-09-19 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0001_initial'),
        ('identification', '0002_identificationreport_verified_by'),
        ('orders', '0003_alter_order_options_order_held_at_order_held_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificationreport',
            name='stone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='orders.stone'),
        ),
        migrations.AddConstraint(
            model_name='identificationreport',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('stone',), name='identification_identificationreport_unique_live_stone'),
        ),
    ]
