# Generated by Django 5.2.17 on 2026-09-23 15:29

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def soft_delete_duplicates(apps, schema_editor):
    """Keep the first live row per (report, instrument) so the constraint holds."""
    InstrumentUsed = apps.get_model("identification", "InstrumentUsed")
    seen = set()
    duplicates = []
    for row in InstrumentUsed.objects.filter(deleted_at__isnull=True).order_by("id"):
        key = (row.report_id, row.instrument_id)
        if key in seen:
            duplicates.append(row.pk)
        seen.add(key)
    InstrumentUsed.objects.filter(pk__in=duplicates).update(deleted_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0001_initial'),
        ('identification', '0003_alter_identificationreport_stone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(soft_delete_duplicates, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='instrumentused',
            name='reading',
        ),
        migrations.AddConstraint(
            model_name='instrumentused',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('report', 'instrument'), name='identification_instrumentused_unique_live'),
        ),
    ]
