# Generated by Django 5.2.17 on 2026-09-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0004_instrumentused_checklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identificationreport',
            name='dimensions',
        ),
    ]
