"""Convert saved treatment enum values to reference rows."""

# Generated by Django 5.2.17 on 2026-10-06 11:58

import django.db.models.deletion
from django.db import migrations, models

TREATMENT_NAMES = {
    "none": "None",
    "heated": "Heated",
    "oiled": "Oiled",
    "dyed": "Dyed",
    "irradiated": "Irradiated",
    "fracture_filled": "Fracture filled",
    "bleached": "Bleached",
    "impregnated": "Impregnated",
}


def migrate_treatments(apps, schema_editor):
    """Move saved enum values to lookup rows without losing report history."""
    treatment_model = apps.get_model("gems", "Treatment")
    report_model = apps.get_model("identification", "IdentificationReport")
    db = schema_editor.connection.alias
    lookups = {}
    existing_values = set(
        report_model.objects.using(db)
        .exclude(treatment="")
        .values_list("treatment", flat=True)
    )
    names_by_code = {
        value: TREATMENT_NAMES.get(value, value) for value in existing_values
    }
    for code, name in names_by_code.items():
        lookup, _ = treatment_model.objects.using(db).get_or_create(name=name)
        lookups[code] = lookup.pk
    for code, treatment_id in lookups.items():
        report_model.objects.using(db).filter(treatment=code).update(
            treatment=treatment_id
        )
    report_model.objects.using(db).filter(treatment="").update(treatment=None)


def reverse_treatments(apps, schema_editor):
    """Restore the former enum codes when rolling the schema back."""
    treatment_model = apps.get_model("gems", "Treatment")
    report_model = apps.get_model("identification", "IdentificationReport")
    db = schema_editor.connection.alias
    codes_by_name = {name: code for code, name in TREATMENT_NAMES.items()}
    for lookup in treatment_model.objects.using(db).all():
        report_model.objects.using(db).filter(treatment=str(lookup.pk)).update(
            treatment=codes_by_name.get(lookup.name, "")
        )
    report_model.objects.using(db).filter(treatment__isnull=True).update(treatment="")


class Migration(migrations.Migration):
    """Convert the report treatment column to a lookup foreign key."""

    dependencies = [
        ("gems", "0003_treatment"),
        ("identification", "0005_drop_dimensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identificationreport",
            name="treatment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("heated", "Heated"),
                    ("oiled", "Oiled"),
                    ("dyed", "Dyed"),
                    ("irradiated", "Irradiated"),
                    ("fracture_filled", "Fracture filled"),
                    ("bleached", "Bleached"),
                    ("impregnated", "Impregnated"),
                ],
                default="",
                max_length=20,
                null=True,
            ),
        ),
        migrations.RunPython(migrate_treatments, reverse_treatments),
        migrations.AlterField(
            model_name="identificationreport",
            name="treatment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="gems.treatment",
            ),
        ),
    ]
