# Generated by Django 5.2.17 on 2026-09-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='comments_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certificate',
            name='dimensions_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='gemmologist_two',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='certificate',
            name='instruments_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='certificate',
            name='nature_type_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='optic_character_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='photo_snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/stones/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='refractive_index_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='report_number_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='shape_cut_snapshot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='certificate',
            name='species_snapshot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='certificate',
            name='specific_gravity_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='transparency_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='treatment_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='variety_snapshot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
