# Generated by Django 5.2.17 on 2026-09-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_comments_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='dimensions_snapshot',
        ),
    ]
