"""Allow certificates to snapshot user-defined treatment names."""

# Generated by Django 5.2.17 on 2026-10-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    """Widen the certificate treatment snapshot column."""

    dependencies = [
        ("certificates", "0003_drop_dimensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="treatment_snapshot",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
