# Generated by Django 5.2.17 on 2026-10-09 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='control_number_sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BillCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('req_id', models.CharField(max_length=100, unique=True)),
                ('reason', models.CharField(max_length=500)),
                ('status_code', models.CharField(blank=True, default='', max_length=30)),
                ('status_desc', models.CharField(blank=True, default='', max_length=255)),
                ('request_xml', models.TextField(blank=True, default='')),
                ('response_xml', models.TextField(blank=True, default='')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellations', to='billing.bill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('req_id', models.CharField(max_length=100, unique=True)),
                ('trx_dt', models.DateField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('ack_id', models.CharField(blank=True, default='', max_length=100)),
                ('ack_status_code', models.CharField(blank=True, default='', max_length=20)),
                ('ack_status_desc', models.CharField(blank=True, default='', max_length=255)),
                ('res_id', models.CharField(blank=True, default='', max_length=100)),
                ('payment_status_code', models.CharField(blank=True, default='', max_length=20)),
                ('payment_status_desc', models.CharField(blank=True, default='', max_length=255)),
                ('request_xml', models.TextField(blank=True, default='')),
                ('acknowledgement_xml', models.TextField(blank=True, default='')),
                ('response_xml', models.TextField(blank=True, default='')),
                ('response_ack_xml', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trx_dt', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cust_cntr_num', models.CharField(blank=True, default='', max_length=30)),
                ('grp_bill_id', models.CharField(blank=True, default='', max_length=100)),
                ('sp_code', models.CharField(blank=True, default='', max_length=20)),
                ('bill_id', models.CharField(blank=True, default='', max_length=100)),
                ('bill_ctr_num', models.CharField(blank=True, default='', max_length=30)),
                ('psp_code', models.CharField(blank=True, default='', max_length=30)),
                ('psp_name', models.CharField(blank=True, default='', max_length=200)),
                ('trx_id', models.CharField(blank=True, default='', max_length=100)),
                ('pay_ref_id', models.CharField(blank=True, default='', max_length=100)),
                ('bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('coll_acc_num', models.CharField(blank=True, default='', max_length=50)),
                ('trx_dt_tm', models.CharField(blank=True, default='', max_length=40)),
                ('raw_xml', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.reconciliation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
