# Generated by Django 5.2.17 on 2026-10-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill_control_number_sms_sent_at_billcancellation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationtransaction',
            name='bill_pay_opt',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='reconciliationtransaction',
            name='pyr_cell_num',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='reconciliationtransaction',
            name='pyr_email',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='reconciliationtransaction',
            name='pyr_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reconciliationtransaction',
            name='qt_ref_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reconciliationtransaction',
            name='rsv1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reconciliationtransaction',
            name='rsv2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reconciliationtransaction',
            name='rsv3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reconciliationtransaction',
            name='trd_pty_trx_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reconciliationtransaction',
            name='usd_pay_chnl',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
