# Generated by Django 5.2.17 on 2026-09-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModuleGate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("module_user", "Can access the user module"),
                    ("module_catalog", "Can access the catalog module"),
                    ("module_settings", "Can access the settings module"),
                    ("module_audit", "Can access the audit module"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
