# Generated by Django 5.2.17 on 2026-09-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modulegate",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("module_orders", "Can access the orders module"),
                    ("module_identification", "Can access the identification module"),
                    ("module_billing", "Can access the billing module"),
                    ("module_certificates", "Can access the certificates module"),
                    ("module_reference", "Can access the reference-data module"),
                    ("module_user", "Can access the user module"),
                    ("module_settings", "Can access the settings module"),
                    ("module_audit", "Can access the audit module"),
                ],
            },
        ),
    ]
