# Generated by Django 5.2.17 on 2026-09-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemLogAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_systemlog", "Can read the application log file")
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
