# Generated by Django 5.2.17 on 2026-09-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_statistics', 'Can view management statistics')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
