# Generated by Django 5.2.17 on 2026-09-25 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('order_received', 'Order received'), ('ready_to_bill', 'Ready to bill'), ('bill_paid', 'Bill paid'), ('certificates_issued', 'Certificates issued')], max_length=40)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True, default='')),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notificatio_recipie_ce9d56_idx')],
            },
        ),
    ]
