# Generated by Django 5.2.17 on 2026-09-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_received', 'Order received'), ('ready_to_bill', 'Ready to bill'), ('bill_paid', 'Bill paid'), ('ready_to_certify', 'Ready to certify'), ('ready_for_collection', 'Ready for collection')], max_length=40),
        ),
    ]
