# Generated by Django 5.2.17 on 2026-09-25 06:15

from django.db import migrations

DEFAULT_CODENAMES = (
    "add_notification",
    "change_notification",
    "delete_notification",
    "view_notification",
)


def drop_default_permissions(apps, schema_editor):
    """Remove the default permissions 0001 created and nothing checks.

    Clearing ``default_permissions`` only stops Django creating them; rows
    already in ``auth_permission`` would linger in the roles matrix as switches
    wired to nothing.
    """
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.filter(
        content_type__app_label="notifications", codename__in=DEFAULT_CODENAMES
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("notifications", "0002_kinds_follow_pipeline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "default_permissions": (),
                "ordering": ["-created_at"],
                "permissions": [
                    ("receive_order_received", "Receive 'Order received' notifications"),
                    ("receive_ready_to_bill", "Receive 'Ready to bill' notifications"),
                    ("receive_bill_paid", "Receive 'Bill paid' notifications"),
                    (
                        "receive_ready_to_certify",
                        "Receive 'Ready to certify' notifications",
                    ),
                    (
                        "receive_ready_for_collection",
                        "Receive 'Ready for collection' notifications",
                    ),
                ],
            },
        ),
        # Nothing to restore on reverse: 0001's options bring them back on the
        # next post_migrate.
        migrations.RunPython(drop_default_permissions, migrations.RunPython.noop),
    ]
